// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_Is1om5Z3E7VnknUzT32v_6Dm6UZ-qU',
    appId: '1:1017200422750:web:5166b2ea4bd36fd4ce29cf',
    messagingSenderId: '1017200422750',
    projectId: 'firstapp-7d5ab',
    authDomain: 'firstapp-7d5ab.firebaseapp.com',
    storageBucket: 'firstapp-7d5ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrc0bw3qoeVdpmitmwaXdPjWXxMQfGaVI',
    appId: '1:1017200422750:android:e52f63249f3f7790ce29cf',
    messagingSenderId: '1017200422750',
    projectId: 'firstapp-7d5ab',
    storageBucket: 'firstapp-7d5ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC46Y9-juhweERJdoQ_4uAUc3tRHcH7x-s',
    appId: '1:1017200422750:ios:b4f3083967ce8de3ce29cf',
    messagingSenderId: '1017200422750',
    projectId: 'firstapp-7d5ab',
    storageBucket: 'firstapp-7d5ab.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC46Y9-juhweERJdoQ_4uAUc3tRHcH7x-s',
    appId: '1:1017200422750:ios:b4f3083967ce8de3ce29cf',
    messagingSenderId: '1017200422750',
    projectId: 'firstapp-7d5ab',
    storageBucket: 'firstapp-7d5ab.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1_Is1om5Z3E7VnknUzT32v_6Dm6UZ-qU',
    appId: '1:1017200422750:web:51e86084c5f2b935ce29cf',
    messagingSenderId: '1017200422750',
    projectId: 'firstapp-7d5ab',
    authDomain: 'firstapp-7d5ab.firebaseapp.com',
    storageBucket: 'firstapp-7d5ab.firebasestorage.app',
  );

}